### PR TITLE
Add mdtest to IOR repo and update backends to support mdtest

### PR DESCRIPTION
**Pull request by hjelmn**
This PR merges the IOR and mdtest repositories so that they can share the aiori infrastructure. I have done some preliminary testing and it is looking good so far.

### CODE REVIEW

**Comment by glennklockwood** [comment]
Thanks for doing all this work.  Unfortunately the changes to the automake process are now preventing me from being able to bootstrap autoconf on either Cray's CLE5.2 or CLE6.0.  Even with a relatively new autoconf (2.69), bootstrap throws:

```
Makefile.am: error: required file './NEWS' not found
Makefile.am: error: required file './AUTHORS' not found
src/Makefile.am:18: warning: compiling 'mdtest.c' with per-target flags requires 'AM_PROG_CC_C_O' in 'configure.ac'
autoreconf: automake failed with exit status: 1
```

I'd love to take a close look at these changes and get them merged in, but I'm on vacation through the first week of July and won't be able to do this in a timely manner.  If this PR is still open when I get back, I can take on the review.

**Comment by hjelmn** [comment]
I forgot to add those required files. Adding them now.

**Comment by hjelmn** [comment]
The initial versions of NEWS and AUTHORS are empty. We should probably start populating those at some point.

**Comment by hjelmn** [comment]
@johnbent FYI.

**Comment by hjelmn** [comment]
Cleaned this up a bit. Should be good to go.

**Comment by ezickler** [comment]
@hjelmn Hi i tried your changes by cloning your repo. I wasn't able to compile it and i think it's because aiori.c is missing. You added it to the Makefile.am in the src folder.

**Comment by glennklockwood** [comment]
+1 to @ezickler's comment.  Autoconf now proceeds, but make fails very quickly:

```
Making all in src
make[1]: Entering directory `/global/u2/g/glock/src/git/ior-hjelmn/src'
make  all-am
make[2]: Entering directory `/global/u2/g/glock/src/git/ior-hjelmn/src'
cc -std=gnu99 -DHAVE_CONFIG_H -I.      -g -O2 -MT ior-ior.o -MD -MP -MF .deps/ior-ior.Tpo -c -o ior-ior.o `test -f 'ior.c' || echo './'`ior.c
mv -f .deps/ior-ior.Tpo .deps/ior-ior.Po
cc -std=gnu99 -DHAVE_CONFIG_H -I.      -g -O2 -MT ior-utilities.o -MD -MP -MF .deps/ior-utilities.Tpo -c -o ior-utilities.o `test -f 'utilities.c' || echo './'`utilities.c
mv -f .deps/ior-utilities.Tpo .deps/ior-utilities.Po
cc -std=gnu99 -DHAVE_CONFIG_H -I.      -g -O2 -MT ior-parse_options.o -MD -MP -MF .deps/ior-parse_options.Tpo -c -o ior-parse_options.o `test -f 'parse_options.c' || echo './'`parse_options.c
mv -f .deps/ior-parse_options.Tpo .deps/ior-parse_options.Po
make[2]: *** No rule to make target `aiori.c', needed by `ior-aiori.o'.  Stop.
make[2]: Leaving directory `/global/u2/g/glock/src/git/ior-hjelmn/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/global/u2/g/glock/src/git/ior-hjelmn/src'
make: *** [all-recursive] Error 1
```

**Comment by hjelmn** [comment]
For some reason I am not getting notifications on comments for this PR. Just noticed them. Will take a look now and fix the issues.

**Comment by hjelmn** [comment]
Fixed.

**Comment by glennklockwood** [comment]
Thanks @hjelmn.  It looks like there's a build target for a man page, but IOR doesn't actually have a man page:

```
cc -std=gnu99  -g -O2    -o mdtest mdtest-mdtest.o mdtest-utilities.o mdtest-aiori.o   mdtest-aiori-MPIIO.o   mdtest-aiori-POSIX.o       
make[2]: Leaving directory '/global/u2/g/glock/src/git/ior-hjelmn/src'
make[1]: Leaving directory '/global/u2/g/glock/src/git/ior-hjelmn/src'
Making all in doc
make[1]: Entering directory '/global/u2/g/glock/src/git/ior-hjelmn/doc'
make[1]: *** No rule to make target 'mdtest.1', needed by 'all-am'.  Stop.
make[1]: Leaving directory '/global/u2/g/glock/src/git/ior-hjelmn/doc'
Makefile:353: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Sorry I can't be more useful here--autoconf is not a strong suit of mine.

**Comment by hjelmn** [comment]
Forgot to add that one too. Should work now.

**Comment by glennklockwood** [comment]
It's now compiling, and cursory tests indicate that IOR continues to work as it did before.  Unfortunately when I naively run mdtest as I have in the past, I get an odd error (tested on NERSC Cori/KNL):

```
Command line used: /global/homes/g/glock/src/git/ior-hjelmn/src/mdtest -e 1 -w 1 -n 1000
08/23/2017 16:50:42: Process 0(): FAILED in main, Could not find suitable backend to use: Permission denied
08/23/2017 16:50:42: Process 1(): FAILED in main, Could not find suitable backend to use: Permission denied
08/23/2017 16:50:42: Process 2(): FAILED in main, Could not find suitable backend to use: Permission denied
08/23/2017 16:50:42: Process 3(): FAILED in main, Could not find suitable backend to use: Permission denied
Rank 0 [Wed Aug 23 16:50:42 2017] [c11-3c0s1n1] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
Rank 1 [Wed Aug 23 16:50:42 2017] [c11-3c0s1n1] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
Rank 2 [Wed Aug 23 16:50:42 2017] [c11-3c0s1n1] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
Rank 3 [Wed Aug 23 16:50:42 2017] [c11-3c0s1n1] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
```

I haven't dug too deep into the code, but I can help debug this as time permits.

So as not to keep this PR sitting in limbo indefinitely, I propose:

1. cutting a new 3.1.0 version of IOR _before_ merging this PR that will encapsulate all of the contributions from LANL and Rob Latham (PLFS, HDFS, S3, etc)
2. doing a cursory set of portability and functionality tests to ensure that IOR and mdtest both work as they did before under the new merged codebase
3. accepting this PR into IOR/master to facilitate broader testing of the merged codebase
4. once we as a community have exercised the merged codebase and all of the edge cases, we cut a new 3.2.0 version of IOR
5. any corner case bugs that crop up in the merged 3.2.0 tree can be addressed as point releases

I've already done Step 1 (the new aioris should've been tagged as new versions since they significant expand the functionality of IOR), and I discovered the aforementioned mdtest issue while attempting Step 2.  We'll have to also tweak the `META` file and some of your added documentation, @hjelmn, but those are minor things we can sort out after the merge.

**Comment by hjelmn** [comment]
Probably a bug in plfs detection. Looking into this today.

**Comment by johnbent** [comment]
I suggest we should cut all the plfs code.  Plfs is dead so hooks into it are deprecated.

**Comment by hjelmn** [comment]
@johnbent Ok, will remove them in a separate commit on this PR.

**Comment by hjelmn** [comment]
Rebased this off the current master and removed plfs support. @glennklockwood Can you test again?

**Comment by glennklockwood** [comment]
Yes, sorry for the long delay on testing this.  I will try to get to it next week.

**Comment by johnbent** [comment]
That’d be awesome bec Jay Lofstead and I spent a long time today working on io500 to make it easier to run. If we had this merged, that’d remove one extra dependency. 

Thanks to Nathan for this awesome contribution!

**Comment by glennklockwood** [comment]
This passes basic smoke testing and I'm comfortable pulling it into master.  We'll have to do more thorough tests across a wider variety of input parameters for both IOR and mdtest, but it's looking great so far.  Thanks for contributing this, @hjelmn!

**Pull request merged**
