### PR TITLE
change MPI_BYTE to MPI_SIGNED_CHAR

### PR DESCRIPTION
**Pull request by lwh1990**
From Pnetcdf 1.7, the MPI datatype corresponding to NC_BYTE  is change from MPI_BYTE to MPI_SIGNED_CHAR. If not change, running IOR with NCMPI will cause a fatal error as below:
ERROR in aiori-NCMPI.c (line 287): cannot write to data set.
ERROR: NetCDF: Not a valid data type or _FillValue type mismatch.

### CODE REVIEW

**Comment by glennklockwood** [comment]
My intuition is that we should support both the earlier pre-1.7 and newer post-1.7 data types, but I don't keep up to date with the pnetcdf community and am unsure if there is a preferred way to address this within pnetcdf itself.  The safest bet is to detect the pnetcdf version via autoconf and set the appropriate data type at configure time.

I'll look into more general solutions and get back to this in the near future.

**Comment by glennklockwood** [comment]
Maybe a dumb question, but is it possible to just use `NC_BYTE` directly within `aiori-NCMPI.c` so we don't have to do a bunch of preprocessor gymnastics every time this data type changes?

**Comment by lwh1990** [comment]
In Pnetcdf, NC_BYTE is need by ncmpi_def_var() which is used to define the data variable. But in IO function such as ncmpi_put_vara() used in IOR will need corresponding MPI datatype as one of its parameter. Maybe there is another solution which doesn't need to provide MPI datatype. Pnetcdf does provide another kind of IO functions like ncmpi_put_var_schar() which do not need MPI datatype as parameter and do the same thing as ncmpi_put_vara(..MPI_SIGNED_CHAR ...). But I am not sure whether old release have support these funtion. I can try and test different version release. If it works, I will pull a request.

**Comment by lwh1990** [comment]
I have added another commit which doesn't need MPI datatype parameter and tested. It works fine with Pnetcdf-1.4.0 (oldest release I can download in official website) and Pnecdf-1.8.1 (newset stable release).

**Pull request merged**
